// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JsonPrettifier;

internal sealed partial class Vsix
{
    public const string Id = "JsonPrettifier.d45ff985-0886-43f0-bd50-8c682a9755b4";
    public const string Name = "JsonPrettifier";
    public const string Description = @"Plain and simple, straight to the point JSON formatter, not restricted to only "".json"" file formats.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Deivid Rodrigues";
    public const string Tags = "";
    public const bool IsPreview = false;
}
